# This file was generated with rails g enum Area

class Area
  include EnumModel

  TYPES = %w[
    agroforestry
    animal_welfare
    aquaculture
    biodiversity
    climate_smart_commodities_practices
    climate_change
    conservation_tillage
    cover_crops
    crop_diversification
    crop_rotation
    drainage
    feed_additives
    fertilizer_efficiency
    fiber_systems
    grazing_management
    prescription_fire
    land_use_conversation
    livestock_partnerships
    methane_livestock
    methane_rice
    nitrogen_management
    nutrient_quality_density
    restoration_of_disturbed_lands
    soil_health
    sustainable_or_biological_inputs
    toxins_reduction
    organic_agriculture
    urban_farming
    water_quality
    water_conservation_and_management_practices
    wetlands
    wildlife_habitat
    reforestation_and_afforestation
    regenerative_agriculture
    watershed_management
    land_conservation
    agrovoltaics
    climate_change_mitigation_strategies
    resilient_crop_systems_development
    on_farm_decarbonization
    journalism_training_and_education
    media_communications_narrative_building
    academic_institution_support_and_capacity
    capacity_building
    education_legislators
    education_future_farmers_young_farmers
    education_youth
    education_funders
    leadership_development
    support_education_capacity_for_government_staff
    technical_assistance_and_business_planning_for_farmers
    business_planning_marketing_for_farmers
    regenerative_agriculture_organizing_networks_or_groups
    community_power_building
    equity_and_justice
    farmworker_rights
    food_sovereignty
    healthy_food_access
    land_access
    land_back_initiatives
    land_tenure
    land_transition
    market_access_and_infrastructure
    tribal_nations
    approved_insurance_providers_and_warranty_products
    farm_equipment
    fintech
    land_asset_financing
    middle_of_the_supply_chain_infrastructure
    regenerative_agriculture_financing
    regenerative_cpgs_brands
    rural_economic_health
    supply_chain_and_market_development
    true_cost_accounting
    farm_bill
    federal_policy_initiatives
    fossil_fuel_based_inputs_alternatives_bioinputs
    insurance_reform_and_alternative_insurance_products
    litigation
    movement_building
    municipal_policy_initiatives
    next_generation_policy_leadership
    policy_advocacy
    policy_lobbying
    public_and_private_finance_mechanisms
    regulatory_work_taking_on_industry
    risk_management_reform
    science_informed_policy_development
    shareholder_advocacy
    state_policy_initiatives
    tackling_fossil_fuels_in_agriculture
    voluntary_incentive_programs
    agtech
    alternative_proteins
    fermentation
    emissions_models_methane_n2o
    genetics
    measurement_monitoring_reporting_and_verification
    on_farm_automation
    research_measuring_and_validation_of_regenerative_systems_and_practices
    research_and_development_innovation
    software
    soil_measurement_and_technology
    supply_equipment
  ].freeze
end
