export const GREOGRAPHIC_SCOPES = [
  {
    id: 'regions',
    name: 'U.S. Regions',
  },
  {
    id: 'states',
    name: 'U.S. States',
  },
  {
    id: 'national',
    name: 'National',
  },
  {
    id: 'countries',
    name: 'Outside U.S.',
  },
];

export const REGIONS = [
  { name: 'Alaska', id: 'AL' },
  { name: 'Mid-Atlantic', id: 'MA' },
  { name: 'Midwest-East North Central and Great Lakes', id: 'GL' },
  { name: 'Midwest-West North Central and Great Plains', id: 'GP' },
  { name: 'Mountain West', id: 'MW' },
  { name: 'New England', id: 'NE' },
  { name: 'Pacific Islands', id: 'PI' },
  { name: 'South Central', id: 'SC' },
  { name: 'Southeast', id: 'SE' },
  { name: 'Southwest', id: 'SW' },
  { name: 'West Coast', id: 'WC' },
];

export const STATES = [
  {
    id: 'AL',
    name: 'Alabama',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'AK',
    name: 'Alaska',
    region: 'Alaska',
    region_id: 'AL',
  },
  {
    id: 'AZ',
    name: 'Arizona',
    region: 'Southwest',
    region_id: 'SW',
  },
  {
    id: 'AR',
    name: 'Arkansas',
    region: 'South Central',
    region_id: 'SC',
  },
  {
    id: 'CA',
    name: 'California',
    region: 'West Coast',
    region_id: 'WC',
  },
  {
    id: 'CO',
    name: 'Colorado',
    region: 'Mountain West',
    region_id: 'MW',
  },
  {
    id: 'CT',
    name: 'Connecticut',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'DE',
    name: 'Delaware',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'DC',
    name: 'District of Columbia',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'FL',
    name: 'Florida',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'GA',
    name: 'Georgia',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'HI',
    name: 'Hawaii',
    region: 'Pacific Islands',
    region_id: 'PI',
  },
  {
    id: 'ID',
    name: 'Idaho',
    region: 'Mountain West',
    region_id: 'MW',
  },
  {
    id: 'IL',
    name: 'Illinois',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'IN',
    name: 'Indiana',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'IA',
    name: 'Iowa',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'KS',
    name: 'Kansas',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'KY',
    name: 'Kentucky',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'LA',
    name: 'Louisiana',
    region: 'South Central',
    region_id: 'SC',
  },
  {
    id: 'ME',
    name: 'Maine',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'MD',
    name: 'Maryland',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'MA',
    name: 'Massachusetts',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'MI',
    name: 'Michigan',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'MN',
    name: 'Minnesota',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'MS',
    name: 'Mississippi',
    region: 'South Central',
    region_id: 'SC',
  },
  {
    id: 'MO',
    name: 'Missouri',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'MT',
    name: 'Montana',
    region: 'Mountain West',
    region_id: 'MW',
  },
  {
    id: 'NE',
    name: 'Nebraska',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'NV',
    name: 'Nevada',
    region: 'Southwest',
    region_id: 'SW',
  },
  {
    id: 'NH',
    name: 'New Hampshire',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'NJ',
    name: 'New Jersey',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'NM',
    name: 'New Mexico',
    region: 'Southwest',
    region_id: 'SW',
  },
  {
    id: 'NY',
    name: 'New York',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'NC',
    name: 'North Carolina',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'ND',
    name: 'North Dakota',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'OH',
    name: 'Ohio',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'OK',
    name: 'Oklahoma',
    region: 'South Central',
    region_id: 'SC',
  },
  {
    id: 'OR',
    name: 'Oregon',
    region: 'West Coast',
    region_id: 'WC',
  },
  {
    id: 'PA',
    name: 'Pennsylvania',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'RI',
    name: 'Rhode Island',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'SC',
    name: 'South Carolina',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'SD',
    name: 'South Dakota',
    region: 'Midwest- West North Central and Great Plains',
    region_id: 'GP',
  },
  {
    id: 'TN',
    name: 'Tennessee',
    region: 'Southeast',
    region_id: 'SE',
  },
  {
    id: 'TX',
    name: 'Texas',
    region: 'South Central',
    region_id: 'SC',
  },
  {
    id: 'UT',
    name: 'Utah',
    region: 'Southwest',
    region_id: 'SW',
  },
  {
    id: 'VT',
    name: 'Vermont',
    region: 'New England',
    region_id: 'NE',
  },
  {
    id: 'VA',
    name: 'Virginia',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'WA',
    name: 'Washington',
    region: 'West Coast',
    region_id: 'WC',
  },
  {
    id: 'WV',
    name: 'West Virginia',
    region: 'Mid-Atlantic',
    region_id: 'MA',
  },
  {
    id: 'WI',
    name: 'Wisconsin',
    region: 'Midwest- East North Central and Great Lakes',
    region_id: 'GL',
  },
  {
    id: 'WY',
    name: 'Wyoming',
    region: 'Mountain West',
    region_id: 'MW',
  },
];

export const COUNTRIES = [
  { id: 'BRA', name: 'Brazil' },
  { id: 'FRA', name: 'France' },
  { id: 'MEX', name: 'Mexico' },
  { id: 'PER', name: 'Peru' },
  { id: 'PHI', name: 'Philippines' },
  { id: 'SPA', name: 'Spain' },
  { id: 'STA', name: 'South Africa' },
  { id: 'USA', name: 'United States of America' },
];

export const SUBGEOGRAPHICS = {
  states: STATES,
  regions: REGIONS,
  countries: COUNTRIES,
  // national: null,
};
